services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: DOCKER_JOURNEY_APP
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307" # default mysql is 3307:3306, internal port is 3306, or use MYSQL_TCP_PORT
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "db" ]
      timeout: 20s
      retries: 10
  api:
    environment:
      DB_HOST: db # or use through machine host ip (ex: '192.168.1.41')
      DB_PORT: 3307 # default mysql is 3307:3306, internal port is 3306, or use MYSQL_TCP_PORT
    build: ../..  # Build the image from the Dockerfile in the parent directory
    ports:
      - '8080:8080' # Expose the API service on port 8080
    depends_on:
      - db  # Ensure the database starts before the API service